### ISSUE TITLE
Compatibility Web3 0.x -> Web3 1.0 

### ISSUE THREAD

**Issue by renexdev** [flyswatter/ethjs-ens#18]
Hi there, I'm trying to use ethjs-ens in a project with Web3 1.0. 
The following code:
```
    let provider = web3.currentProvider
    provider.sendAsync = provider.send
    console.log(provider)
    const ens = new ENS( provider, registryAddress)
```
gives me 
`error: The EthJsENS Constructor requires a provider.`
Do you know any way to handdle this? Thanks in advance...

**Comment by danfinlay** [comment]
Look at the sample code. These are not two ordered arguments, they are options in a hash:
```
 const ens = new ENS({ provider, network: '3' })

// is the same as:
 const ens = new ENS({ provider: provider, network: '3' })
```

**Comment by renexdev** [comment]
Great, thanks!
